# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-18 18:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('av', '0006_auto_20180425_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedmedia',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadedmedia',
            name='update_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadedmediaimage',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_image_create_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
