# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-16 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'date created')),
                ('lastupdated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'date updated')),
                ('file', models.FileField(upload_to=b'activitylog/%Y/%m/')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activitylog_create_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded Activity Log',
                'verbose_name_plural': 'Uploaded Activity Log',
            },
        ),
    ]
