# Generated by Django 2.1.7 on 2019-03-21 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activitylog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedactivitylog',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='uploadedactivitylog',
            name='file',
            field=models.FileField(upload_to='activitylog/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='uploadedactivitylog',
            name='lastupdated_date',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name='date updated'),
        ),
    ]
