# Generated by Django 2.2.13 on 2020-11-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_delete_settingproperties'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursedailystats',
            options={'verbose_name': 'CourseDailyStats',
                     'verbose_name_plural': 'CourseDailyStats'},
        ),
        migrations.AlterModelOptions(
            name='usercoursesummary',
            options={'verbose_name': 'UserCourseSummary',
                     'verbose_name_plural': 'UserCourseSummaries'},
        ),
        migrations.AlterModelOptions(
            name='userpointssummary',
            options={'verbose_name': 'UserPointsSummary',
                     'verbose_name_plural': 'UserPointsSummaries'},
        ),
        migrations.CreateModel(
            name='DailyActiveUsers',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('day', models.DateField()),
                ('total_submitted_date', models.IntegerField(default=0)),
                ('total_tracker_date', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'DailyActiveUsers',
                'verbose_name_plural': 'DailyActiveUsers',
                'unique_together': {('day', 'total_submitted_date')},
                'index_together': {('day', 'total_submitted_date')},
            },
        ),
    ]
