# Generated by Django 2.2.13 on 2020-11-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0006_dailyactiveuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactiveuser',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
    ]
