# Generated by Django 2.2.24 on 2021-08-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0009_auto_20210701_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyactiveusers',
            options={'verbose_name': 'DailyActiveUserDay',
                     'verbose_name_plural': 'DailyActiveUserDays'},
        ),
    ]
