# Generated by Django 3.2.13 on 2022-06-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0012_usercoursedailysummary'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyactiveusers',
            unique_together=None,
        ),
        migrations.AlterIndexTogether(
            name='dailyactiveusers',
            index_together=None,
        ),
        migrations.DeleteModel(
            name='DailyActiveUser',
        ),
        migrations.DeleteModel(
            name='DailyActiveUsers',
        ),
    ]
