# Generated by Django 4.2.7 on 2023-12-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0013_remove_dailyactiveuser'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='coursedailystats',
            index_together=set(),
        ),
    ]
