# Generated by Django 4.2.7 on 2023-12-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0014_alter_coursedailystats_index_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coursedailystats',
            index=models.Index(fields=['course', 'day', 'type'], name='summary_cou_course__15569d_idx'),
        ),
    ]
