# Generated by Django 4.2.7 on 2023-12-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0015_coursedailystats_summary_cou_course__15569d_idx'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='usercoursesummary',
            index_together=set(),
        ),
    ]
