# Generated by Django 4.2.7 on 2023-12-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0016_alter_usercoursesummary_index_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usercoursesummary',
            index=models.Index(fields=['user', 'course'], name='summary_use_user_id_03479d_idx'),
        ),
    ]
