# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20150524_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='uuid',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
