# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-21 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20180518_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='event',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='points',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
