# Generated by Django 2.1.7 on 2019-03-21 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20180612_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='question',
            name='lastupdated_date',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('multichoice',
                                             'Multiple choice'),
                                            ('shortanswer',
                                             'Short answer'),
                                            ('matching',
                                             'Matching'),
                                            ('numerical',
                                             'Numerical'),
                                            ('multiselect',
                                             'Multiple select'),
                                            ('description',
                                             'Information only'),
                                            ('essay',
                                             'Essay question')],
                                   default='multichoice',
                                   max_length=15),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lastupdated_date',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='attempt_date',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name='date attempted'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='submitted_date',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name='date submitted'),
        ),
        migrations.AlterField(
            model_name='response',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='response',
            name='lastupdated_date',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name='date updated'),
        ),
    ]
