# Generated by Django 2.2.8 on 2019-12-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20191228_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'verbose_name': 'QuizAttempt', 'verbose_name_plural': 'QuizAttempts'},
        ),
    ]
