# Generated by Django 2.2.8 on 2019-12-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20191225_1118'),
        ('quiz', '0011_auto_20191228_1413'),
    ]

    operations = [
    ]
