# Generated by Django 2.1.12 on 2020-01-21 13:40

import ast
from django.db import migrations

from oppia.uploader import clean_lang_dict


def clean_quiz_dicts(apps, schema_editor):
    clean_quiz_model(apps)
    clean_question_model(apps)
    clean_response_model(apps)


def clean_quiz_model(apps):
    quiz_model = apps.get_model("quiz", "Quiz")
    for quiz in quiz_model.objects.all():
        try:
            if '{' in quiz.title:
                title = ast.literal_eval(quiz.title)
                quiz.title = clean_lang_dict(title)
            if '{' in quiz.description:
                description = ast.literal_eval(quiz.description)
                quiz.description = clean_lang_dict(description)
            quiz.save()
        except SyntaxError:
            pass


def clean_question_model(apps):
    question_model = apps.get_model("quiz", "Question")
    for q in question_model.objects.all():
        try:
            if '{' in q.title:
                title = ast.literal_eval(q.title)
                q.title = clean_lang_dict(title)
                q.save()
        except SyntaxError:
            pass


def clean_response_model(apps):
    response_model = apps.get_model("quiz", "Response")
    for r in response_model.objects.all():
        try:
            if '{' in r.title:
                title = ast.literal_eval(r.title)
                r.title = clean_lang_dict(title)
                r.save()
        except SyntaxError:
            pass


def noop(app, schema_editor):
    # this migration is not reversible
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_merge_20191228_1740'),
    ]

    operations = [
        migrations.RunPython(clean_quiz_dicts, noop),
    ]
