# Generated by Django 2.2.10 on 2020-03-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_cleanup_quiz_dicts'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
    ]
