
MAX_UPLOAD_SIZE = 'MAX_UPLOAD_SIZE'
OPPIA_ALLOW_SELF_REGISTRATION = 'OPPIA_ALLOW_SELF_REGISTRATION'
OPPIA_CARTODB_ACCOUNT = 'OPPIA_CARTODB_ACCOUNT'
OPPIA_CARTODB_KEY = 'OPPIA_CARTODB_KEY'
OPPIA_HOSTNAME = 'OPPIA_HOSTNAME'
