
MAX_UPLOAD_SIZE = 'MAX_UPLOAD_SIZE'
OPPIA_ALLOW_SELF_REGISTRATION = 'OPPIA_ALLOW_SELF_REGISTRATION'
OPPIA_CARTODB_ACCOUNT = 'OPPIA_CARTODB_ACCOUNT'
OPPIA_CARTODB_KEY = 'OPPIA_CARTODB_KEY'
OPPIA_HOSTNAME = 'OPPIA_HOSTNAME'

CRON_DATETIME_FORMAT = '%Y-%m-%d %H:%M:%S.%f+00:00'
OPPIA_CRON_LAST_RUN = 'oppia_cron_last_run'
OPPIA_SUMMARY_CRON_LAST_RUN = 'oppia_summary_cron_last_run'