
MAX_UPLOAD_SIZE = 'MAX_UPLOAD_SIZE'
OPPIA_ALLOW_SELF_REGISTRATION = 'OPPIA_ALLOW_SELF_REGISTRATION'
OPPIA_HOSTNAME = 'OPPIA_HOSTNAME'

CRON_DATETIME_FORMAT = '%Y-%m-%d %H:%M:%S.%f+00:00'
OPPIA_CRON_LAST_RUN = 'oppia_cron_last_run'
OPPIA_SUMMARY_CRON_LAST_RUN = 'oppia_summary_cron_last_run'

OPPIA_SHOW_GRAVATARS = 'OPPIA_SHOW_GRAVATARS'

# Gamification
OPPIA_POINTS_ENABLED = 'OPPIA_POINTS_ENABLED'
OPPIA_BADGES_ENABLED = 'OPPIA_BADGES_ENABLED'
OPPIA_BADGES_PERCENT_COMPLETED = 'OPPIA_BADGES_PERCENT_COMPLETED'

# Google and Android
OPPIA_GOOGLE_ANALYTICS_ENABLED = 'OPPIA_GOOGLE_ANALYTICS_ENABLED'
OPPIA_ANDROID_ON_GOOGLE_PLAY = 'OPPIA_ANDROID_ON_GOOGLE_PLAY'

OPPIA_GOOGLE_ANALYTICS_CODE = 'OPPIA_GOOGLE_ANALYTICS_CODE'
OPPIA_GOOGLE_ANALYTICS_DOMAIN = 'OPPIA_GOOGLE_ANALYTICS_DOMAIN'
OPPIA_ANDROID_PACKAGEID = 'OPPIA_ANDROID_PACKAGEID'

# Map visualisations
OPPIA_MAP_VISUALISATION_ENABLED = 'OPPIA_MAP_VISUALISATION_ENABLED'
OPPIA_CARTODB_ACCOUNT = 'OPPIA_CARTODB_ACCOUNT'
OPPIA_CARTODB_KEY = 'OPPIA_CARTODB_KEY'
OPPIA_IPSTACK_APIKEY = 'OPPIA_IPSTACK_APIKEY'

# Data retention policy
OPPIA_DATA_RETENTION_YEARS = 'OPPIA_DATA_RETENTION_YEARS'
