# Generated by Django 2.2.5 on 2019-11-29 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_customfield_userprofilecustomfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customfield',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofilecustomfield',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofilecustomfield',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
