# Generated by Django 2.2.5 on 2019-12-01 10:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0002_customfield_userprofilecustomfield'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofilecustomfield',
            unique_together={('key_name', 'user')},
        ),
    ]
