# Generated by Django 2.2.24 on 2022-04-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20220310_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='exclude_from_reporting',
            field=models.BooleanField(default=False, help_text='If checked, the activity from this user will not be taken into account for summary calculations and reports', verbose_name='Exclude from reporting'),
        ),
    ]
