LEADERBOARD_HOMEPAGE_RESULTS_PER_PAGE = 10
LEADERBOARD_TABLE_RESULTS_PER_PAGE = 25
ACTIVITY_GRAPH_DEFAULT_NO_DAYS = 31
STR_DATE_DISPLAY_FORMAT = "%d %b %Y"
STR_DATE_DISPLAY_FORMAT_MONTH = "%b %Y"

STR_DATE_FORMAT = "%Y-%m-%d"
STR_DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"
