# Generated by Django 2.2.9 on 2020-02-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_insert_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingproperties',
            name='key',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='settingproperties',
            name='str_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
