# Generated by Django 2.2.9 on 2020-02-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_auto_20200201_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingproperties',
            name='bool_value',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
