# Generated by Django 2.2.13 on 2020-10-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_ipstack_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingproperties',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
