# Generated by Django 2.2.24 on 2021-08-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_setting_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingproperties',
            options={'ordering': ['category', 'key'],
                     'verbose_name': 'Settings',
                     'verbose_name_plural': 'Settings'},
        ),
    ]
