# Generated by Django 2.1.7 on 2019-03-21 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20160203_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardaccesslog',
            name='access_date',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name='date created'),
        ),
    ]
