# Generated by Django 3.2.13 on 2022-05-04 09:15

from django.db import migrations, models
from dbview.helpers import CreateView


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20210716_1644'),
        ('profile', '0005_userprofile_exclude_from_reporting'),
        ('summary', '0012_usercoursedailysummary'),
        ('oppia', '0046_course_new_downloads_enabled'),
    ]

    operations = [
        CreateView(
            name='ViewUserCourseCompletePercent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
