# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-13 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0012_fix_future_tracker_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=100, null=True),
        ),
    ]
