# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-18 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0014_auto_20180517_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='event',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
