# Generated by Django 2.1.7 on 2019-03-21 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0018_auto_20180612_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='award_date',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name='date awarded'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='default_icon',
            field=models.FileField(upload_to='badges'),
        ),
        migrations.AlterField(
            model_name='course',
            name='badge_icon',
            field=models.FileField(blank=True,
                                   default=None,
                                   upload_to='badges'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lastupdated_date',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'),
                                            ('student', 'Student')],
                                   max_length=20),
        ),
        migrations.AlterField(
            model_name='points',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='points',
            name='type',
            field=models.CharField(choices=[('signup', 'Sign up'),
                                            ('userquizattempt',
                                             'Quiz attempt by user'),
                                            ('firstattempt',
                                             'First quiz attempt'),
                                            ('firstattemptscore',
                                             'First attempt score'),
                                            ('firstattemptbonus',
                                             'Bonus for first attempt score'),
                                            ('quizattempt',
                                             'Quiz attempt'),
                                            ('quizcreated',
                                             'Created quiz'),
                                            ('activitycompleted',
                                             'Activity completed'),
                                            ('mediaplayed',
                                             'Media played'),
                                            ('badgeawarded',
                                             'Badge awarded'),
                                            ('coursedownloaded',
                                             'Course downloaded')],
                                   max_length=20),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='icon',
            field=models.FileField(blank=True,
                                   default=None,
                                   null=True,
                                   upload_to='tags'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='submitted_date',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name='date submitted'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='tracker_date',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name='date tracked'),
        ),
    ]
