# Generated by Django 2.2.5 on 2019-10-25 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oppia', '0019_auto_20190321_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePublishingLog',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('new_version', models.BigIntegerField()),
                ('old_version', models.BigIntegerField(null=True)),
                ('log_date',
                 models.DateTimeField(default=django.utils.timezone.now,
                                      verbose_name='log_date')),
                ('action', models.CharField(max_length=100)),
                ('data', models.TextField()),
                ('course',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='oppia.Course')),
                ('user',
                 models.ForeignKey(null=True,
                                   on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Publishing Log',
                'verbose_name_plural': 'Course Publishing Logs',
            },
        ),
    ]
