# Generated by Django 2.2.10 on 2020-02-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0021_auto_20191025_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
