# Generated by Django 2.2.13 on 2020-10-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0024_auto_20200923_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title'],
                     'verbose_name': 'Course',
                     'verbose_name_plural': 'Courses'},
        ),
    ]
