# Generated by Django 2.2.13 on 2020-11-09 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0025_auto_20201015_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='submitted_date',
            field=models.DateTimeField(db_index=True,
                                       default=django.utils.timezone.now,
                                       verbose_name='date submitted'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='tracker_date',
            field=models.DateTimeField(db_index=True,
                                       default=django.utils.timezone.now,
                                       verbose_name='date tracked'),
        ),
    ]
