# Generated by Django 2.2.13 on 2020-12-06 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0026_auto_20201109_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeMethod',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='badge',
            name='default_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oppia.BadgeMethod'),
        ),
    ]
