# Generated by Django 2.2.13 on 2021-02-16 18:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oppia', '0028_badge_award_methods'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseTag',
            new_name='CourseCategory',
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name': 'Course Category',
                     'verbose_name_plural': 'Course Categories'},
        ),
        migrations.RenameField(
            model_name='coursecategory',
            old_name='tag',
            new_name='category',
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category',
                     'verbose_name_plural': 'Categories'},
        ),
    ]
