# Generated by Django 2.2.13 on 2021-02-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0028_badge_award_methods'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseTag',
            new_name='CourseCategory',
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name': 'Course Category', 'verbose_name_plural': 'Course Categories'},
        ),
    ]
