# Generated by Django 2.2.13 on 2021-02-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0029_rename_coursetag_to_coursecategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecategory',
            old_name='tag',
            new_name='category',
        ),
    ]
