# Generated by Django 2.2.20 on 2021-05-11 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oppia', '0029_rename_tag_to_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('image_file', models.FileField(
                    upload_to='certificate/templates')),
                ('include_name', models.BooleanField(default=True)),
                ('include_date', models.BooleanField(default=True)),
                ('include_course_title', models.BooleanField(default=True)),
                ('name_x', models.IntegerField(default=0)),
                ('name_y', models.IntegerField(default=0)),
                ('date_x', models.IntegerField(default=0)),
                ('date_y', models.IntegerField(default=0)),
                ('course_title_x', models.IntegerField(default=0)),
                ('course_title_y', models.IntegerField(default=0)),
                ('badge', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='oppia.Badge')),
                ('course', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='oppia.Course')),
            ],
            options={
                'verbose_name': 'Certificate Template',
                'verbose_name_plural': 'Certificate Templates',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='certificates')),
                ('certificate_template', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='oppia.CertificateTemplate')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
            },
        ),
    ]
