# Generated by Django 2.2.21 on 2021-06-07 10:42

from django.db import migrations, models
import oppia.models.badges


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0033_auto_20210531_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='validation',
            field=models.CharField(choices=[('NONE', 'None'), ('QRCODE', 'QR Code'), ('URL', 'URL')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='validation_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='validation_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='image_file',
            field=models.ImageField(help_text='Use a .png image of 842px by 595px (at 72dpi), or use equivalent dimension ratio for higher dpi', upload_to='certificate/templates', validators=[oppia.models.badges.CertificateTemplate.validate_image]),
        ),
    ]
