# Generated by Django 2.2.21 on 2021-06-07 14:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0034_auto_20210607_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='validation_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
