# Generated by Django 2.2.21 on 2021-06-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0035_award_validation_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
    ]
