# Generated by Django 2.2.24 on 2021-06-25 17:16

from django.db import migrations, models
import django.db.models.deletion
import oppia.models.badges


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_populate_time_taken'),
        ('profile', '0003_auto_20191201_1049'),
        ('oppia', '0036_award_emailed'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='display_name_method',
            field=models.CharField(choices=[
                ('USER_FIRST_LAST', 
                 'From user profile - firstname/lastname'),
                ('REGISTRATION_FIELD', 'From registration form field'),
                ('FEEDBACK_RESPONSE', 'From feedback response')
                ], default='USER_FIRST_LAST', max_length=50),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='feedback_field',
            field=models.ForeignKey(blank=True,
                                    default=None,
                                    null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='quiz.QuizQuestion'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='registration_form_field',
            field=models.ForeignKey(blank=True,
                                    default=None,
                                    null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='profile.CustomField'),
        ),
    ]
