# Generated by Django 2.2.24 on 2021-06-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0038_auto_20210625_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='display_name_method',
            field=models.CharField(choices=[
                ('USER_FIRST_LAST', 'User profile - firstname/lastname'),
                ('REGISTRATION_FIELD', 'Registration form field'),
                ('FEEDBACK_RESPONSE', 'Feedback response')],
                default='USER_FIRST_LAST',
                max_length=50),
        ),
    ]
