# Generated by Django 2.2.24 on 2021-07-16 16:44

from django.db import migrations, models
import oppia.models.badges


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0039_auto_20210627_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='image_file',
            field=models.ImageField(
                help_text='Use a .png image of 842px by 595px (at 72dpi), or \
                use equivalent dimension ratio for higher dpi',
                upload_to='certificate/templates',
                validators=[
                    oppia.models.badges.CertificateTemplate.validate_image]),
        ),
    ]
