# Generated by Django 2.2.24 on 2021-11-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0041_auto_20210816_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='course_version',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
