# Generated by Django 2.2.24 on 2022-04-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0044_auto_20220310_0656'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['course', 'user'], name='oppia_track_course__2b7c86_idx'),
        ),
    ]
