# Generated by Django 2.2.27 on 2022-04-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0045_tracker_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='new_downloads_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
