# Generated by Django 3.2.13 on 2022-05-03 06:38

from django.db import migrations, models

from oppia.models import CourseStatus


def migrate_course_status(apps, schema_editor):
    course_model = apps.get_model('oppia', 'Course')
    for course in course_model.objects.all():
        if course.is_archived:
            course.status = CourseStatus.ARCHIVED
        elif course.is_draft:
            course.status = CourseStatus.DRAFT
        elif not course.new_downloads_enabled:
            course.status = CourseStatus.NEW_DOWNLOADS_DISABLED
        else:
            course.status = CourseStatus.LIVE

        course.save()


def reverse_func(apps, schema_editor):
    migrations.RemoveField(
        model_name='course',
        name='status',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0046_course_new_downloads_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(
                choices=[('live', 'Live'),
                         ('draft', 'Draft'),
                         ('archived', 'Archived'),
                         ('new_downloads_disabled', 'New downloads disabled')],
                null=True,
                help_text='More details about each status can be found in the '
                          '<a href=https://oppiamobile.readthedocs.io/en/latest/implementers/courses/statuses.html>'
                          'documentation.</a><br>Note that statuses new-downloads-disabled and read-only are only '
                          'compatible with app version 7.3.9 or above.',
                max_length=100),
        ),
        migrations.RunPython(migrate_course_status, reverse_func),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(
                choices=[('live', 'Live'),
                         ('draft', 'Draft'),
                         ('archived', 'Archived'),
                         ('new_downloads_disabled', 'New downloads disabled')],
                default='live',
                help_text='More details about each status can be found in the '
                          '<a href=https://oppiamobile.readthedocs.io/en/latest/implementers/courses/statuses.html>'
                          'documentation.</a><br>Note that statuses new-downloads-disabled and read-only are only '
                          'compatible with app version 7.3.9 or above.',
                max_length=100),
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='course',
            name='new_downloads_enabled',
        ),
    ]
