# Generated by Django 3.2.13 on 2022-05-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0047_auto_20220503_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(
                choices=[('live', 'Live'),
                         ('draft', 'Draft'),
                         ('archived', 'Archived'),
                         ('new_downloads_disabled', 'New downloads disabled'),
                         ('read_only', 'Read only')],
                default='live',
                help_text='More details about each status can be found in the '
                          '<a href=https://oppiamobile.readthedocs.io/en/latest/implementers/courses/statuses.html> '
                          'documentation.</a><br>Note that statuses new-downloads-disabled and read-only are only '
                          'compatible with app version 7.3.9 or above.',
                max_length=100),
        ),
    ]
