# Generated by Django 3.2.13 on 2022-07-03 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0049_auto_20220601_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStatus',
            fields=[
                ('name', models.CharField(primary_key=True, serialize=False, choices=[('live', 'Live'), ('draft', 'Draft'), ('archived', 'Archived'), ('new_downloads_disabled', 'New downloads disabled'), ('read_only', 'Read only')], default='live', help_text='More details about each status can be found in the <a href=https://oppiamobile.readthedocs.io/en/latest/implementers/courses/statuses.html>documentation.</a><br>Note that statuses new-downloads-disabled and read-only are only compatible with app version 7.3.9 or above.', max_length=100)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Course Status',
                'verbose_name_plural': 'Course Statuses',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='status_fk',
            field=models.ForeignKey(limit_choices_to=models.Q(('available', True)), null=True, on_delete=django.db.models.deletion.PROTECT, to='oppia.coursestatus'),
        ),
    ]
