# Generated by Django 3.2.13 on 2022-07-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0049_auto_20220601_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='restricted',
            field=models.BooleanField(default=False, help_text='Restrict visibility to cohorts'),
        ),
    ]
