# Generated by Django 3.2.13 on 2022-07-03 15:47

from django.db import migrations


def migrate_status_fk(apps, schema_editor):
    course_model = apps.get_model('oppia', 'Course')
    course_status_model = apps.get_model('oppia', 'CourseStatus')
    for course in course_model.objects.all():
        course.status_fk, created = course_status_model.objects.get_or_create(name=course.status)
        course.save()


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0050_auto_20220703_1746'),
    ]

    operations = [
        migrations.RunPython(migrate_status_fk)
    ]
