# Generated by Django 3.2.14 on 2022-07-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0050_course_restricted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(help_text='More details about each status can be found in the <a href=https://oppiamobile.readthedocs.io/en/latest/implementers/courses/statuses.html>documentation.</a><br>Note that statuses new-downloads-disabled and read-only are only compatible with app version 7.3.9 or above.', max_length=100),
        ),
    ]
