# Generated by Django 3.2.14 on 2022-07-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0051_alter_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
