# Generated by Django 3.2.13 on 2022-07-03 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0051_auto_20220703_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='status_fk',
            new_name='status',
        ),
    ]
