# Generated by Django 3.2.14 on 2022-08-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0052_auto_20220726_0900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['id'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='cohort',
            options={'ordering': ['id'], 'verbose_name': 'Cohort', 'verbose_name_plural': 'Cohorts'},
        ),
    ]
