# Generated by Django 2.2.13 on 2020-11-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('av', '0008_auto_20190321_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedmedia',
            name='license',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedmedia',
            name='organisation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='uploadedmedia',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
