# Generated by Django 2.2.24 on 2021-07-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('av', '0009_auto_20201101_1738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedMediaImage',
        ),
    ]
