# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_auto_20180517_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultGamificationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('level', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('helper_text', models.TextField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'Default Gamification Event',
                'verbose_name_plural': 'Default Gamification Events',
            },
        ),
    ]
