# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_defaultgamificationevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultgamificationevent',
            name='level',
            field=models.CharField(choices=[(b'global', b'Global'),
                                            (b'course', b'Course'),
                                            (b'activity', b'Activity'),
                                            (b'quiz', b'Quiz'),
                                            (b'media', b'Media')],
                                   max_length=20),
        ),
    ]
