# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-10 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_auto_20190514_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizgamificationevent',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizgamificationevent',
            name='user',
        ),
        migrations.DeleteModel(
            name='QuizGamificationEvent',
        ),
    ]
