# Generated by Django 2.1.9 on 2019-07-24 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    STR_DATE_CREATED = 'date created'

    dependencies = [
        ('gamification', '0006_auto_20190625_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitygamificationevent',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name=STR_DATE_CREATED),
        ),
        migrations.AlterField(
            model_name='coursegamificationevent',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name=STR_DATE_CREATED),
        ),
        migrations.AlterField(
            model_name='defaultgamificationevent',
            name='level',
            field=models.CharField(choices=[('global', 'Global'),
                                            ('course', 'Course'),
                                            ('activity', 'Activity'),
                                            ('quiz', 'Quiz'),
                                            ('media', 'Media')],
                                   max_length=20),
        ),
        migrations.AlterField(
            model_name='mediagamificationevent',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name=STR_DATE_CREATED),
        ),
    ]
